# Generated by Django 3.2.4 on 2021-06-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitutde', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
